export const CHAT_HISTORY_PAGE_SIZE = 30;
export const CHAT_HISTORY_SCROLL_THRESHOLD_PX = 120;
export const CHAT_BOTTOM_THRESHOLD_PX = 160;
export const CHAT_CACHED_MESSAGE_LIMIT = CHAT_HISTORY_PAGE_SIZE;

